apiVersion: v1
kind: Service
metadata:
  name: medibook-user-info-service
spec:
  type: LoadBalancer
  selector:
    app: medibook-user-info
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP