apiVersion: v1
kind: Service
metadata:
  name: medibook-user-info-ms-service
spec:
  type: LoadBalancer
  selector:
    app: medibook-user-info-ms
  ports:
  - port: 4001
    targetPort: 4001
    protocol: TCP